# Generated by Django 5.2 on 2025-04-25 06:03

import django.db.models.deletion
import hitcount.models
import meta.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='english title')),
                ('content', models.TextField(null=True, verbose_name='content')),
                ('content_en', models.TextField(null=True, verbose_name='english content')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='slug')),
                ('featured_image', models.ImageField(blank=True, upload_to='blog/images/%Y/%m/%d/', verbose_name='featured_image')),
                ('status', models.CharField(choices=[('draft', 'draft'), ('published', 'published')], default='draft', max_length=10, verbose_name='status')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('published', models.DateTimeField(blank=True, null=True, verbose_name='published')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'ordering': ['-published'],
                'indexes': [models.Index(fields=['-published'], name='blog_post_publish_493ec4_idx'), models.Index(fields=['status'], name='blog_post_status_02ce19_idx'), models.Index(fields=['slug'], name='blog_post_slug_cdb902_idx')],
            },
            bases=(meta.models.ModelMeta, models.Model, hitcount.models.HitCountMixin),
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('comments', models.TextField(max_length=300, null=True, verbose_name='Comments')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('status', models.CharField(choices=[('draft', 'draft'), ('allowed', 'Allowed')], default='draft', max_length=10, null=True, verbose_name='status')),
                ('blog_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['-created'], name='blog_commen_created_4b74b7_idx'), models.Index(fields=['status'], name='blog_commen_status_8b5519_idx'), models.Index(fields=['full_name'], name='blog_commen_full_na_fa8b56_idx')],
            },
        ),
    ]
