"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os
from decouple import config
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

if DEBUG:
	ALLOWED_HOSTS = []
else:	
	ALLOWED_HOSTS = ['hamed-biglari.ir','www.hamed-biglari.ir']

# Application definition

INSTALLED_APPS = [
	"unfold",  # before django.contrib.admin
    "unfold.contrib.filters",  # optional, if special filters are needed
    "unfold.contrib.forms",  # optional, if special form elements are needed
    "unfold.contrib.inlines",  # optional, if special inlines are needed
    "unfold.contrib.guardian",  # optional, if django-guardian package is used
    "unfold.contrib.simple_history",  # optional, if django-simple-history package is used
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'django.contrib.humanize',
	'django.contrib.sites',
	'django.contrib.sitemaps',
	'account.apps.AccountConfig',
	'resume.apps.ResumeConfig',
	'tools.apps.ToolsConfig',
	'tinymce',
	'django_cleanup.apps.CleanupConfig',
	'captcha',
	'modeltranslation',
	"crispy_forms",
	'meta',
    'hitcount',
	'blog',

]

MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.locale.LocaleMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'
SITE_ID = 1
TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [BASE_DIR / 'templates'],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
				
			],
		},
	},
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases



DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.postgresql',
		'NAME':  config("POSTGRES_DB"),
		'USER':  config("POSTGRES_USER"),
		'PASSWORD': config("POSTGRES_PASSWORD"),
		'HOST':  config("POSTGRES_HOST"),
	}
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/



TIME_ZONE = 'Asia/Tehran'



LANGUAGE_CODE = 'fa'
USE_I18N = True
USE_L10N = True
USE_TZ = True
LANGUAGES = [
	('fa', 'Persian'),
	('en', 'English'),
]
LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)


PARLER_LANGUAGES = {
    None: (
        {'code': 'fa'},
        {'code': 'en'},
    ),
    'default': {
        'fallbacks': ['fa'],  # زبان پیش‌فرض
        'hide_untranslated': False,
    }
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/
STATIC_URL = '/static/'

MEDIA_URL = '/media/'

if DEBUG:
	STATICFILES_DIRS = [
		BASE_DIR / 'static', 
	]
	MEDIA_ROOT = BASE_DIR / 'media'
else:
	STATIC_ROOT = os.path.join(BASE_DIR, '/static')
	MEDIA_ROOT = os.path.join(BASE_DIR, '/media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'account.User'

TINYMCE_DEFAULT_CONFIG = {
    'height': 500,
    'menubar': True,
    'plugins': (
        "advlist autolink lists link image charmap print preview anchor "
        "searchreplace visualblocks code fullscreen insertdatetime media table paste "
        "wordcount help directionality codesample emoticons hr pagebreak "
        "nonbreaking save template"
    ),
    'toolbar': (
        "undo redo | styleselect | "
        "bold italic underline strikethrough | forecolor backcolor | "
        "alignleft aligncenter alignright alignjustify | "
        "bullist numlist outdent indent | link image media | "
        "charmap emoticons codesample | "
        "ltr rtl | removeformat | fullscreen preview code help"
    ),
    'toolbar_mode': 'wrap',
    'branding': False,
    'statusbar': True,
    'contextmenu': False,
    'forced_root_block': 'p',
}


RECAPTCHA_PUBLIC_KEY = '6LcUn7EkAAAAABPWsdu0LbckuE8AWCduMrR5NKlM'
RECAPTCHA_PRIVATE_KEY = '6LcUn7EkAAAAAGjoqMA2ThXwc3l2ZXTcZGSFBNP0'

CRISPY_TEMPLATE_PACK = "unfold_crispy"

CRISPY_ALLOWED_TEMPLATE_PACKS = ["unfold_crispy"]

UNFOLD = {
    "SITE_HEADER": "CV Admin",
	"SHOW_LANGUAGES": True,
    "DASHBOARD_CALLBACK": "tools.views.dashboard_callback",
}
